#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LOG_DIR="${ROOT}/.foundry/state/hooks"
SUMMARY_PATH="${LOG_DIR}/foundry-acceptance.summary.txt"
HOOK_EVENT_PATH="${LOG_DIR}/last-stop-hook-event.json"

mkdir -p "${LOG_DIR}"
cd "${ROOT}"

if [[ "${FOUNDRY_ACCEPTANCE_HOOK_ACTIVE:-}" == "1" ]]; then
  exit 0
fi
export FOUNDRY_ACCEPTANCE_HOOK_ACTIVE=1

if ! command -v pnpm >/dev/null 2>&1; then
  node - <<'NODE'
const message = 'pnpm was not found on PATH. Foundry acceptance Stop hook skipped; install pnpm 11.23.0 or run pnpm acceptance:check manually.';
console.log(JSON.stringify({ systemMessage: message }));
NODE
  exit 0
fi

if [[ ! -f package.json || ! -f scripts/foundry.mjs ]]; then
  node - <<'NODE'
const message = 'Foundry acceptance Stop hook skipped because package.json or scripts/foundry.mjs was not found at the repository root.';
console.log(JSON.stringify({ systemMessage: message }));
NODE
  exit 0
fi

cat > "${HOOK_EVENT_PATH}" || true

set +e
pnpm acceptance:check > "${SUMMARY_PATH}" 2>&1
status=$?
set -e

if [[ "${status}" -eq 0 ]]; then
  exit 0
fi

FOUNDRY_HOOK_STATUS="${status}" \
FOUNDRY_HOOK_ROOT="${ROOT}" \
FOUNDRY_HOOK_SUMMARY="${SUMMARY_PATH}" \
node - <<'NODE'
const fs = require('node:fs');
const path = require('node:path');

const root = process.env.FOUNDRY_HOOK_ROOT;
const summaryPath = process.env.FOUNDRY_HOOK_SUMMARY;
const latestPath = path.join(root, '.foundry/state/acceptance/latest.json');
const promptPath = path.join(root, '.foundry/state/acceptance/continuation-prompt.md');

function readText(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return '';
  }
}

function readJson(filePath) {
  try {
    return JSON.parse(readText(filePath));
  } catch {
    return null;
  }
}

const summary = readText(summaryPath).trim();
const latest = readJson(latestPath);
const prompt = readText(promptPath).trim();
const latestFailed = latest?.status === 'failed';
const failedReports = latestFailed && Array.isArray(latest?.reports)
  ? latest.reports.filter((report) => report.status !== 'passed')
  : [];

const reportLines = failedReports.map((report) => {
  const pieces = [
    `- contract: ${report.contract_path}`,
    `  report: ${report.report_path}`,
  ];
  if (report.continuation_prompt_path) {
    pieces.push(`  prompt: ${report.continuation_prompt_path}`);
  }
  return pieces.join('\n');
});

const reason = [
  'Foundry acceptance checks found blocking failures, so do not finalize this turn yet.',
  'Use the generated report, update the concrete artifact or contract failure, then rerun `pnpm acceptance:check`.',
  'Finish only after blocking checks pass.',
  '',
  latestFailed ? `Acceptance report: ${latestPath.replace(`${root}/`, '')}` : 'Acceptance report was not generated by this failed hook run or the previous report is stale.',
  reportLines.length ? reportLines.join('\n') : '',
  '',
  latestFailed && prompt ? prompt : summary || `pnpm acceptance:check exited with status ${process.env.FOUNDRY_HOOK_STATUS}.`,
].filter(Boolean).join('\n');

console.log(JSON.stringify({
  decision: 'block',
  reason,
}, null, 2));
NODE

exit 0
