#!/usr/bin/env node
import { createAuthoringPlanCommands } from "./commands/authoring-plan.ts";
import { createBafuAutoAuthoringCommands } from "./commands/bafu-auto-authoring.ts";
import { createBafuBatchImportRunCommands } from "./commands/bafu-batch-import-run.ts";
import { createBafuLeafClassificationTaskCommands } from "./commands/bafu-leaf-classification-tasks.ts";
import { createBafuProcessScopeE2eCommands } from "./commands/bafu-process-scope-e2e.ts";
import { createBundleSampleRowsCommands } from "./commands/bundle-sample-rows.ts";
import { createCliWrapperCommands } from "./commands/cli-wrappers.ts";
import { createCommitHandoffCommands } from "./commands/commit-handoff.ts";
import { createCoreCommands } from "./commands/core.ts";
import { createExecutionCapsuleCommands } from "./commands/execution-capsule.ts";
import { createIdentityDecisionTaskCommands } from "./commands/identity-decision-task.ts";
import { createIdentityDecisionCommands } from "./commands/identity-decisions.ts";
import { createIdentityPreflightRunCommands } from "./commands/identity-preflight-run.ts";
import { createIdentityReferenceRewriteCommands } from "./commands/identity-reference-rewrites.ts";
import { createImportCompletionCommands } from "./commands/import-completion.ts";
import { createImportLedgerCommands } from "./commands/import-ledger.ts";
import { createIncrementalChangeSetCommands } from "./commands/incremental-change-set.ts";
import { createLibraryScopeWorkflowCommands } from "./commands/library-scope-workflow.ts";
import { createPostAuthoringFinalizeCommands } from "./commands/post-authoring-finalize.ts";
import { createPostWriteCloseoutCommands } from "./commands/post-write-closeout.ts";
import { createSupportCacheCommands } from "./commands/support-cache.ts";
import { createTaskCommands } from "./commands/tasks.ts";
import { createTidasWorkflowCommands } from "./commands/tidas-workflow.ts";
import { createTopologyConvergenceCommands } from "./commands/topology-convergence.ts";
import { createUslciBatchImportRunCommands } from "./commands/uslci-batch-import-run.ts";
import { createWorldsteelBatchImportRunCommands } from "./commands/worldsteel-batch-import-run.ts";
import { bundleRowTypes } from "./lib/bundle-row-types.ts";
import { createBundleSampleUtils } from "./lib/bundle-sample-utils.ts";
import { createCanonicalSupportRewriteUtils } from "./lib/canonical-support-rewrites.ts";
import { createDecisionTaskUtils } from "./lib/decision-task-utils.ts";
import { parseArgs, parseScalar } from "./lib/foundry-args.ts";
import { runFoundryCli } from "./lib/foundry-cli.ts";
import { exitCodeForCommand, usage } from "./lib/foundry-command-registry.ts";
import { createFoundryRuntimeUtils } from "./lib/foundry-runtime-utils.ts";
import { resolveFoundryRuntimePaths } from "./lib/foundry-runtime-paths.ts";
import { createFullContextProofUtils } from "./lib/full-context-proof.ts";
import { createIdentityPreflightArtifactUtils } from "./lib/identity-preflight-artifacts.ts";
import { createIdentityReferenceRewriteUtils } from "./lib/identity-reference-rewrite-utils.ts";
import {
  foundryTraceSummary,
  listImportProfiles,
  profileFor,
  runDatasetAuthoringPatchCollect,
  runDatasetAuthoringTaskBuild,
  runDatasetCurationCleanup,
  runDatasetCurationGate,
  runDatasetMutationManifest,
} from "./lib/import-curation.ts";
import { normalizeUtcDateTimeString } from "./lib/import-curation/internal/prewrite-cleanup.ts";
import { createImportLedgerUtils } from "./lib/import-ledger.ts";
import { createLocationQualityUtils } from "./lib/location-quality-utils.ts";
import { createPostAuthoringFinalizeUtils } from "./lib/post-authoring-finalize-utils.ts";
import { createSourceSemanticUtils } from "./lib/source-semantics.ts";
import {
  runTidasHandshake,
  runTidasImport,
  runTidasPackageValidation,
  runTidasRowsValidation,
} from "./lib/tidas-adapter.ts";
import { createTidasRowUtils } from "./lib/tidas-row-utils.ts";
import { createTraceCoverageUtils } from "./lib/trace-coverage.ts";

const { repoRoot } = resolveFoundryRuntimePaths(import.meta.url);
const foundryTraceNamespace = "https://tiangong-lca.dev/foundry/import-curation/1";

type DependencyFactory = (dependencies: never) => unknown;

function bindFactory<Factory extends DependencyFactory>(
  factory: Factory,
  dependencies: unknown,
): ReturnType<Factory> {
  return factory(dependencies as never) as ReturnType<Factory>;
}

const {
  appendOption,
  appendRepeatedOptions,
  asText,
  blockersFromLocationAuditStage,
  booleanOption,
  cloneJson,
  compactStageReport,
  countJsonLinesFile,
  countRowsFile,
  deterministicUuid,
  directoryExists,
  ensureArray,
  fileExists,
  findFilesByName,
  hasUnresolvedAiPlaceholder,
  integerOption,
  isPlaceholderEnvValue,
  jsonSha256,
  loadRuntimeEnv,
  normalizedList,
  nowIso,
  positiveIntegerOption,
  postAuthoringPrewriteGateBlockers,
  readJson,
  readJsonArtifactOption,
  readJsonLines,
  readJsonOrJsonLines,
  readRowsFile,
  readText,
  replaceFrontmatterField,
  reportFileFromCliStage,
  reportInputPath,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  resolveTiangongLcaCliCommand,
  resolveTiangongLcaCliCommandPrefix,
  resolveTiangongLcaCliBin,
  runTiangongJsonStage,
  sameResolvedPath,
  sha256Text,
  shellQuote,
  skippedPrewriteStage,
  splitFrontmatter,
  taskMetaFromFile,
  unique,
  writeJson,
  writeText,
} = bindFactory(createFoundryRuntimeUtils, { parseScalar, repoRoot });

loadRuntimeEnv();

const {
  bundleClassificationPath,
  cleanEcoSpoldNameText,
  contactGlobalReference,
  datasetIdentity,
  datasetRowsFileStem,
  flowClassificationSchemaType,
  flowTypeOfDataSet,
  isConvertedDefaultClassification,
  isObjectEmpty,
  languageForText,
  multiLang,
  pathExpression,
  preferredSourceLanguageText,
  printJson,
  rewriteContactReferences,
  sanitizePlaceholderText,
  textValue,
  writeJsonLines,
} = bindFactory(createTidasRowUtils, {
  asText,
  bundleRowTypes,
  cloneJson,
  ensureArray,
  writeText,
});

const {
  classificationQueueSchemaType,
  classificationQueueRowType,
  classificationQueueInputRows,
  classificationQueueOutputRows,
  hasQueueSelectionOptions,
  selectDecisionTaskQueueRows,
  safeFileToken,
  decisionTaskChunkLabel,
  rewriteDecisionTaskQueueRowsForChunk,
  decisionTaskInputRowsOverride,
  classificationDecisionSchemaType,
  classificationDecisionTargetKey,
  classificationQueueTargetKey,
  classificationDecisionCode,
  classificationDecisionUsedContextKinds,
  buildClassificationTaskProvenanceContext,
  decisionTaskContextFileSummary,
  dedupeDecisionTaskContextFiles,
  writeDecisionTaskSharedContextBundle,
  buildDecisionTaskContextBundle,
  decisionAuthoringContext,
  buildClassificationDecisionTaskContextFiles,
  decisionTaskContextBlockers,
  decisionTaskBuildStatus,
  readDecisionTaskProofs,
  decisionContextBundleSha256,
  decisionCompletionStatus,
  decisionTaskReportPayload,
  decisionTaskProofList,
  decisionTaskContextBundleHashes,
} = bindFactory(createDecisionTaskUtils, {
  asText,
  cloneJson,
  ensureArray,
  fileExists,
  integerOption,
  normalizedList,
  nowIso,
  positiveIntegerOption,
  readJson,
  readJsonLines,
  readText,
  repoRelativePath,
  resolveRepoPath,
  sameResolvedPath,
  sha256Text,
  unique,
  writeJson,
});

const { completionFullContextBlockers, fullContextProofCheck, profileFullContextRequirement } =
  bindFactory(createFullContextProofUtils, {
    asText,
    classificationDecisionUsedContextKinds,
    decisionCompletionStatus,
    decisionContextBundleSha256,
    ensureArray,
    fileExists,
    listImportProfiles,
    normalizedList,
    readJson,
    readJsonArtifactOption,
    readJsonLines,
    readText,
    repoRelativePath,
    resolveRepoPath,
    repoRoot,
    sha256Text,
    unique,
  });

const { validateTraceQueueCoverageForRows } = bindFactory(createTraceCoverageUtils, {
  asText,
  datasetIdentity,
  fileExists,
  foundryTraceSummary,
  readJsonLines,
  readRowsFile,
  repoRelativePath,
  resolveRepoPath,
});

const {
  applyCanonicalSupportRewrites,
  loadCanonicalSupportCache,
  rewriteCanonicalFlowPropertyReferences,
  supportText,
} = bindFactory(createCanonicalSupportRewriteUtils, {
  asText,
  booleanOption,
  cloneJson,
  datasetIdentity,
  datasetRowsFileStem,
  ensureArray,
  fileExists,
  multiLang,
  nowIso,
  pathExpression,
  readJson,
  readRowsFile,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  writeJson,
  writeJsonLines,
});

const coreCommands = bindFactory(createCoreCommands, {
  ensureArray,
  fileExists,
  isPlaceholderEnvValue,
  listImportProfiles,
  normalizedList,
  nowIso,
  readJson,
  readText,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  splitFrontmatter,
  unique,
  writeJson,
});

const taskCommands = bindFactory(createTaskCommands, {
  asText,
  booleanOption,
  completionFullContextBlockers,
  directoryExists,
  ensureArray,
  fileExists,
  nowIso,
  readJsonArtifactOption,
  replaceFrontmatterField,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  taskMetaFromFile,
  writeText,
});

const executionCapsuleCommands = bindFactory(createExecutionCapsuleCommands, { repoRoot });
const incrementalChangeSetCommands = bindFactory(createIncrementalChangeSetCommands, { repoRoot });
const topologyConvergenceCommands = bindFactory(createTopologyConvergenceCommands, { repoRoot });
const tidasWorkflowCommands = bindFactory(createTidasWorkflowCommands, {
  repoRoot,
  runTidasHandshake,
  runTidasImport,
  runTidasPackageValidation,
  runTidasRowsValidation,
});

const cliWrapperCommands = bindFactory(createCliWrapperCommands, {
  appendOption,
  appendRepeatedOptions,
  repoRoot,
  resolveTiangongLcaCliCommand,
  resolveTiangongLcaCliBin,
});

const commitHandoffCommands = bindFactory(createCommitHandoffCommands, {
  appendOption,
  asText,
  countJsonLinesFile,
  fileExists,
  fullContextProofCheck,
  nowIso,
  profileFor,
  readJsonArtifactOption,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  resolveTiangongLcaCliCommand,
  resolveTiangongLcaCliBin,
  shellQuote,
  validateTraceQueueCoverageForRows,
  writeJson,
});

const importLedgerUtils = bindFactory(createImportLedgerUtils, {
  asText,
  datasetIdentity,
  fileExists,
  nowIso,
  readJson,
  readJsonLines,
  repoRelativePath,
  resolveRepoPath,
  writeJson,
});

const importLedgerCommands = bindFactory(createImportLedgerCommands, {
  runDatasetImportLedgerReport: importLedgerUtils.runDatasetImportLedgerReport,
});

const postWriteCloseoutCommands = bindFactory(createPostWriteCloseoutCommands, {
  asText,
  countJsonLinesFile,
  countRowsFile,
  datasetIdentity,
  ensureArray,
  fileExists,
  fullContextProofCheck,
  nowIso,
  readJsonArtifactOption,
  readJsonLines,
  readRowsFile,
  repoRelativeMaybe,
  repoRelativePath,
  reportInputPath,
  resolveRepoPath,
  sameResolvedPath,
  validateTraceQueueCoverageForRows,
  writeCloseoutImportLedger: importLedgerUtils.writeCloseoutImportLedger,
  writeJson,
});

const importCompletionCommands = bindFactory(createImportCompletionCommands, {
  asText,
  countJsonLinesFile,
  countRowsFile,
  fileExists,
  findFilesByName,
  fullContextProofCheck,
  normalizedList,
  nowIso,
  readJson,
  readJsonArtifactOption,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  sameResolvedPath,
  unique,
  writeJson,
});

const supportCacheCommands = bindFactory(createSupportCacheCommands, {
  resolveTiangongLcaCliCommand,
  asText,
  ensureArray,
  fileExists,
  nowIso,
  readJson,
  repoRelativePath,
  resolveRepoPath,
  supportText,
  writeJson,
});

const {
  buildBafuFallbackSourcePayload,
  buildDatabaseFallbackSourcePayload,
  buildBafuProcessContextSourcePayload,
  canonicalSourceReferenceForRelation,
  processOriginalSourceMetadata,
  processSourceReferenceRows,
  repairTrueSourceClassification,
  repairTrueSourceDescription,
  repairTrueSourceIdentity,
  rewriteCanonicalSourceReferences,
  rewriteProcessDataSourceReferences,
  rewriteTrueSourceReferenceDescriptions,
  sourceReferenceSemanticBlockers,
  sourceReferenceSnapshot,
  sourceSummaryMatchesOriginalMetadata,
  sourceSemanticSummary,
} = bindFactory(createSourceSemanticUtils, {
  asText,
  bundleClassificationPath,
  cloneJson,
  datasetIdentity,
  deterministicUuid,
  languageForText,
  multiLang,
  pathExpression,
  repoRelativeMaybe,
  textValue,
});

const {
  addDedupedBundleRow,
  buildLibraryContactPayload,
  collectBundleQualityFindings,
  collectElementaryFlowReuseFindings,
  collectSourceTracePayloads,
  findFirstBundleContactTemplate,
  flowNameParts,
  listProcessBundleDirs,
  processAuthoringContextFromTrace,
  processSourceClassificationSummary,
  sanitizeBundlePayload,
  selectProcessBundleDirs,
  sourceTraceLocationCode,
} = bindFactory(createBundleSampleUtils, {
  asText,
  bundleClassificationPath,
  canonicalSourceReferenceForRelation,
  cloneJson,
  contactGlobalReference,
  datasetIdentity,
  deterministicUuid,
  directoryExists,
  ensureArray,
  fileExists,
  flowClassificationSchemaType,
  flowTypeOfDataSet,
  isConvertedDefaultClassification,
  isObjectEmpty,
  jsonSha256,
  languageForText,
  multiLang,
  normalizeUtcDateTimeString,
  normalizedList,
  nowIso,
  pathExpression,
  readJson,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  sanitizePlaceholderText,
  sourceReferenceSnapshot,
  textValue,
});

const {
  attachIdentityPreflightRows,
  buildIdentityPreflightArtifacts,
  identityPreflightSourceIndexPaths,
  loadIdentityPreflightSourceFileMap,
} = bindFactory(createIdentityPreflightArtifactUtils, {
  asText,
  bundleClassificationPath,
  cleanEcoSpoldNameText,
  collectSourceTracePayloads,
  datasetIdentity,
  ensureArray,
  fileExists,
  flowNameParts,
  flowTypeOfDataSet,
  isConvertedDefaultClassification,
  jsonSha256,
  normalizedList,
  processAuthoringContextFromTrace,
  processSourceClassificationSummary,
  readJson,
  readJsonLines,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  safeFileToken,
  sha256Text,
  shellQuote,
  sourceTraceLocationCode,
  textValue,
  writeJson,
  writeJsonLines,
});

const {
  classificationAuthoringCommands,
  collectLocationQualityFindings,
  loadTidasLocationCodeMap,
  locationAuthoringCommands,
} = bindFactory(createLocationQualityUtils, {
  asText,
  bundleRowTypes,
  datasetIdentity,
  directoryExists,
  ensureArray,
  fileExists,
  pathExpression,
  readJson,
  repoRelativeMaybe,
  repoRelativePath,
  repoRoot,
  shellQuote,
});

const identityPreflightCommands = bindFactory(createIdentityPreflightRunCommands, {
  asText,
  booleanOption,
  buildIdentityPreflightArtifacts,
  datasetIdentity,
  ensureArray,
  fileExists,
  identityPreflightSourceIndexPaths,
  integerOption,
  jsonSha256,
  loadIdentityPreflightSourceFileMap,
  normalizedList,
  nowIso,
  positiveIntegerOption,
  readJson,
  readJsonLines,
  readRowsFile,
  repoRelativeMaybe,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  resolveTiangongLcaCliCommand,
  resolveTiangongLcaCliCommandPrefix,
  resolveTiangongLcaCliBin,
  safeFileToken,
  sha256Text,
  shellQuote,
  writeJson,
  writeJsonLines,
  writeText,
});

const libraryScopeWorkflowCommands = bindFactory(createLibraryScopeWorkflowCommands, {
  asText,
  booleanOption,
  profileFor,
  repoRoot,
  bundleClassificationPath,
  cloneJson,
  datasetIdentity,
  directoryExists,
  ensureArray,
  fileExists,
  flowTypeOfDataSet,
  jsonSha256,
  nowIso,
  positiveIntegerOption,
  readJson,
  readJsonLines,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  sha256Text,
  textValue,
  writeJson,
  writeJsonLines,
});

const bafuProcessScopeE2eCommands = bindFactory(createBafuProcessScopeE2eCommands, {
  booleanOption,
  fileExists,
  nowIso,
  readJson,
  readJsonLines,
  readRowsFile,
  repoRelativeMaybe,
  resolveRepoPath,
  shellQuote,
  textValue,
  writeJson,
});
const batchImportRunDeps = {
  asText: textValue,
  booleanOption,
  datasetIdentity,
  directoryExists,
  fileExists,
  integerOption,
  normalizedList,
  nowIso,
  readJson,
  readJsonLines,
  repoRelativeMaybe,
  resolveRepoPath,
  shellQuote,
  writeJson,
  writeJsonLines,
};
const bafuBatchImportRunCommands = bindFactory(
  createBafuBatchImportRunCommands,
  batchImportRunDeps,
);
const uslciBatchImportRunCommands = bindFactory(
  createUslciBatchImportRunCommands,
  batchImportRunDeps,
);
const worldsteelBatchImportRunCommands = bindFactory(
  createWorldsteelBatchImportRunCommands,
  batchImportRunDeps,
);
const bafuLeafClassificationTaskCommands = bindFactory(createBafuLeafClassificationTaskCommands, {
  asText: textValue,
  ensureArray,
  integerOption,
  nowIso,
  positiveIntegerOption,
  readJson,
  readJsonLines,
  repoRelativeMaybe,
  resolveRepoPath,
  writeJson,
  writeJsonLines,
});
const bafuAutoAuthoringCommands = bindFactory(createBafuAutoAuthoringCommands, {
  ensureArray,
  fileExists,
  nowIso,
  readJson,
  readText,
  repoRelativePath,
  resolveRepoPath,
  writeJson,
  writeJsonLines,
});

const {
  applyIdentityReferenceRewrites,
  externalizeUnresolvedProcessFlowExchanges,
  identityReferenceRewriteIndexPath,
  referenceShortDescription,
} = bindFactory(createIdentityReferenceRewriteUtils, {
  asText,
  cloneJson,
  countRowsFile,
  datasetIdentity,
  datasetRowsFileStem,
  ensureArray,
  fileExists,
  foundryTraceNamespace,
  identityPreflightCommands,
  languageForText,
  multiLang,
  normalizedList,
  nowIso,
  pathExpression,
  preferredSourceLanguageText,
  readJson,
  readJsonLines,
  readRowsFile,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  supportText,
  unique,
  writeJson,
  writeJsonLines,
});

const {
  runFinalizeAutoCurationQueue,
  runFinalizeIdentityPreflightStage,
  sourceReferenceRewritesFileForRowsFile,
} = bindFactory(createPostAuthoringFinalizeUtils, {
  asText,
  booleanOption,
  cliWrapperCommands,
  countRowsFile,
  datasetIdentity,
  ensureArray,
  fileExists,
  identityPreflightCommands,
  identityReferenceRewriteIndexPath,
  normalizedList,
  readRowsFile,
  referenceShortDescription,
  repoRelativeMaybe,
  resolveRepoPath,
  unique,
  writeJsonLines,
});

const authoringPlanCommands = bindFactory(createAuthoringPlanCommands, {
  appendOption,
  appendRepeatedOptions,
  asText,
  datasetRowsFileStem,
  decisionTaskChunkLabel,
  ensureArray,
  fileExists,
  hasUnresolvedAiPlaceholder,
  normalizedList,
  nowIso,
  positiveIntegerOption,
  readJson,
  readJsonOrJsonLines,
  repoRelativeMaybe,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  safeFileToken,
  shellQuote,
  unique,
  writeJson,
});

const identityReferenceRewriteCommands = bindFactory(createIdentityReferenceRewriteCommands, {
  applyIdentityReferenceRewrites,
  asText,
  datasetRowsFileStem,
  fileExists,
  nowIso,
  repoRelativePath,
  resolveRepoPath,
  writeJson,
});

const identityDecisionCommands = bindFactory(createIdentityDecisionCommands, {
  asText,
  datasetIdentity,
  datasetRowsFileStem,
  fileExists,
  flowTypeOfDataSet,
  hasUnresolvedAiPlaceholder,
  normalizedList,
  nowIso,
  profileFor,
  readJson,
  readJsonLines,
  readRowsFile,
  readText,
  referenceShortDescription,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  sha256Text,
  unique,
  writeJson,
  writeJsonLines,
});

const identityDecisionTaskCommands = bindFactory(createIdentityDecisionTaskCommands, {
  asText,
  datasetRowsFileStem,
  decisionAuthoringContext,
  decisionTaskBuildStatus,
  decisionTaskContextFileSummary,
  dedupeDecisionTaskContextFiles,
  ensureArray,
  fileExists,
  hasQueueSelectionOptions,
  normalizedList,
  nowIso,
  readJson,
  readText,
  repoRelativePath,
  repoRoot,
  resolveRepoPath,
  selectDecisionTaskQueueRows,
  sha256Text,
  shellQuote,
  unique,
  writeDecisionTaskSharedContextBundle,
  writeJson,
  writeJsonLines,
});

const postAuthoringFinalizeCommands = bindFactory(createPostAuthoringFinalizeCommands, {
  appendOption,
  applyCanonicalSupportRewrites,
  loadCanonicalSupportCache,
  applyIdentityReferenceRewrites,
  asText,
  profileFor,
  blockersFromLocationAuditStage,
  buildLibraryContactPayload,
  booleanOption,
  compactStageReport,
  cloneJson,
  contactGlobalReference,
  datasetIdentity,
  datasetRowsFileStem,
  ensureArray,
  externalizeUnresolvedProcessFlowExchanges,
  fileExists,
  normalizedList,
  nowIso,
  postAuthoringPrewriteGateBlockers,
  processSourceReferenceRows,
  profileFullContextRequirement,
  repoRelativeMaybe,
  repoRelativePath,
  repoRoot,
  reportFileFromCliStage,
  resolveRepoPath,
  repairTrueSourceClassification,
  repairTrueSourceDescription,
  repairTrueSourceIdentity,
  rewriteCanonicalSourceReferences,
  rewriteContactReferences,
  rewriteTrueSourceReferenceDescriptions,
  runDatasetCommitHandoffPlan: commitHandoffCommands.runDatasetCommitHandoffPlan,
  runDatasetCurationCleanup,
  runDatasetCurationGate,
  runDatasetMutationManifest,
  runFinalizeAutoCurationQueue,
  runFinalizeIdentityPreflightStage,
  runTidasRowsValidation: (options: Record<string, unknown>) =>
    runTidasRowsValidation({ repoRoot, options }),
  runTiangongJsonStage,
  skippedPrewriteStage,
  sourceReferenceSemanticBlockers,
  sourceReferenceRewritesFileForRowsFile,
  sourceSemanticSummary,
  readRowsFile,
  unique,
  writeFinalizeImportLedger: importLedgerUtils.writeFinalizeImportLedger,
  writeJson,
  writeJsonLines,
});

const bundleSampleRowsCommands = bindFactory(createBundleSampleRowsCommands, {
  addDedupedBundleRow,
  asText,
  attachIdentityPreflightRows,
  booleanOption,
  profileFor,
  repoRoot,
  buildBafuFallbackSourcePayload,
  buildDatabaseFallbackSourcePayload,
  buildBafuProcessContextSourcePayload,
  buildIdentityPreflightArtifacts,
  buildLibraryContactPayload,
  classificationAuthoringCommands,
  cloneJson,
  collectBundleQualityFindings,
  collectElementaryFlowReuseFindings,
  collectLocationQualityFindings,
  collectSourceTracePayloads,
  contactGlobalReference,
  datasetIdentity,
  ensureArray,
  fileExists,
  findFirstBundleContactTemplate,
  listProcessBundleDirs,
  loadCanonicalSupportCache,
  loadTidasLocationCodeMap,
  locationAuthoringCommands,
  nowIso,
  processOriginalSourceMetadata,
  processSourceReferenceRows,
  readJson,
  repairTrueSourceClassification,
  repairTrueSourceDescription,
  repairTrueSourceIdentity,
  repoRelativeMaybe,
  repoRelativePath,
  resolveRepoPath,
  resolveTiangongLcaCliCommandPrefix,
  resolveTiangongLcaCliBin,
  rewriteCanonicalFlowPropertyReferences,
  rewriteCanonicalSourceReferences,
  rewriteProcessDataSourceReferences,
  rewriteContactReferences,
  rewriteTrueSourceReferenceDescriptions,
  sanitizeBundlePayload,
  selectProcessBundleDirs,
  shellQuote,
  sourceReferenceSemanticBlockers,
  sourceSummaryMatchesOriginalMetadata,
  sourceSemanticSummary,
  textValue,
  writeJson,
  writeJsonLines,
});

runFoundryCli({
  commandDeps: {
    authoringPlanCommands,
    uslciBatchImportRunCommands,
    worldsteelBatchImportRunCommands,
    bafuAutoAuthoringCommands,
    bafuBatchImportRunCommands,
    bafuLeafClassificationTaskCommands,
    bafuProcessScopeE2eCommands,
    bundleSampleRowsCommands,
    cliWrapperCommands,
    commitHandoffCommands,
    coreCommands,
    executionCapsuleCommands,
    identityDecisionCommands,
    identityDecisionTaskCommands,
    identityPreflightCommands,
    identityReferenceRewriteCommands,
    incrementalChangeSetCommands,
    importCompletionCommands,
    importLedgerCommands,
    libraryScopeWorkflowCommands,
    listImportProfiles,
    postAuthoringFinalizeCommands,
    postWriteCloseoutCommands,
    repoRoot,
    runDatasetAuthoringPatchCollect,
    runDatasetAuthoringTaskBuild,
    runDatasetCurationCleanup,
    runDatasetCurationGate,
    runDatasetMutationManifest,
    supportCacheCommands,
    taskCommands,
    tidasWorkflowCommands,
    topologyConvergenceCommands,
  },
  decisionDeps: {
    asText,
    buildClassificationDecisionTaskContextFiles,
    buildClassificationTaskProvenanceContext,
    buildDecisionTaskContextBundle,
    classificationDecisionCode,
    classificationDecisionSchemaType,
    classificationDecisionTargetKey,
    classificationDecisionUsedContextKinds,
    classificationQueueInputRows,
    classificationQueueOutputRows,
    classificationQueueRowType,
    classificationQueueSchemaType,
    classificationQueueTargetKey,
    compactStageReport,
    datasetIdentity,
    decisionAuthoringContext,
    decisionCompletionStatus,
    decisionContextBundleSha256,
    decisionTaskBuildStatus,
    decisionTaskChunkLabel,
    decisionTaskContextBlockers,
    decisionTaskContextBundleHashes,
    decisionTaskContextFileSummary,
    decisionTaskInputRowsOverride,
    decisionTaskProofList,
    decisionTaskReportPayload,
    ensureArray,
    fileExists,
    hasQueueSelectionOptions,
    hasUnresolvedAiPlaceholder,
    nowIso,
    readDecisionTaskProofs,
    readJsonOrJsonLines,
    repoRelativeMaybe,
    repoRelativePath,
    repoRoot,
    resolveRepoPath,
    rewriteDecisionTaskQueueRowsForChunk,
    runTiangongJsonStage,
    selectDecisionTaskQueueRows,
    shellQuote,
    unique,
    writeJson,
    writeJsonLines,
  },
  runtime: { exitCodeForCommand, parseArgs, printJson, usage },
});
